### ISSUE TITLE
Error loading Virtualshop v1.7, plugin is disabled!

### ISSUE THREAD

**Issue by darkboomba** [EmilJimenez21/VirtualShop#1]
Hi!

I'm trying to install Virtualshop on my 1.12.2 Towny server (paperspigot). I love the idea of the plugin and I think it will help with my economy.

However it doesn't wanna load! I get the following error and I don't what I can do to fix it. https://pastebin.com/KKm08WxB

I'm using MySQL and the plugin does connect to it and has succesfuly made it's entries into it.
Let me know if you need any other information.

Thanks!

**Comment by EmilJimenez21** [comment]
@darkboomba Thank you for submitting this error! Would you be able to provide me the paper release number you are using so I can better debug this issue?

EDIT: I've identified the issue and a potential fix. I'm going to be implementing a quick fix for this and make this apart of a new milestone to create a custom item database

**Comment by EmilJimenez21** [comment]
Version 1.8 is now live on SpigotMC with backwards compatibility for older MC versions with the Material tag
