### ISSUE TITLE
List of perms?

### ISSUE THREAD

**Issue by Smale2** [EmilJimenez21/VirtualShop#3]

**Comment by EmilJimenez21** [comment]
/buy <amount> <item> [maxprice] - **virtualshop.buy** - Buys an item.
/sell <amount:all> <item:hand> <price> - **virtualshop.sell** - Sells an item.
/find <item> - **virtualshop.find** - Finds all listings for the specified item.
/stock [player] [page] - **virtualshop.stock** - Finds items that a player has for sale.
/sales [player] [page] - **virtualshop.sales** - Finds all transactions for the specified player.
/shop - Displays a command reference guide.

**Comment by EmilJimenez21** [comment]
All the permissions can be found on the Spigot page under commands
