### ISSUE TITLE
Buy Command fails if price is not given.

### ISSUE THREAD

**Issue by NekoShinobi** [EmilJimenez21/VirtualShop#4]
Price is listed as an optional parameter, but if it's left null, the command fails.

So either the syntax needs to change to show that it's mandatory, or the buy command needs to be fixed.

This seems to be the culprit:

https://github.com/EmilJimenez21/VirtualShop/blob/master/src/main/java/me/emiljimenez21/virtualshop/commands/Buy.java#L115

**Comment by EmilJimenez21** [comment]
Thank you for the report, I'll work on a fix right away!

**Comment by EmilJimenez21** [comment]
Issue resolved in latest release
