### ISSUE TITLE
Ancient_debris and Netherite_scrap doesnt work

### ISSUE THREAD

**Issue by AiJermain** [EmilJimenez21/VirtualShop#8]
People are able to list set items but whenever you want to buy them they will say that no one is selling them :/

**Comment by EmilJimenez21** [comment]
Hi @AiJermain,

Would you please provide the logs, if any so I can look into this further? I haven't experienced this issue yet.

The commands are sensitive, for example: If you post 5 diamond ore to buy 5 diamond ore you would have to use /buy diamond_ore 5. 

As an added note: I'm working on making a GUI for this plugin to remove the use of any commands which should be released in a weeks time :)
