### ISSUE TITLE
Support for the sale of nbt tagged items 

### ISSUE THREAD

**Issue by Omri100** [EmilJimenez21/VirtualShop#9]
Hi, I've been wondering if there would ever be a possibility of selling nbt tagged items such as potions and enchanted books using the plugin, the plugin is amazing and the players on my servers love it, but wish to sell these items through their stocks aswell.

**Comment by EmilJimenez21** [comment]
Hi @Omri100,

Would you be willing to hop on Discord to talk about this?

**Comment by Omri100** [comment]
sure thing, where do I find you?
